### PR TITLE
fix file creation, removed -n character

### PR DESCRIPTION
**Pull request by christian-fei**
First of all, THANK YOU!
This should fix the `-n` character in the output file.

### CODE REVIEW

**Comment by zakjan** [comment]
Hi Christian, thanks for your contribution!

I use `echo -n` to clear the file if it already exists. It doesn't work for you?

I suspect you use OSX, because I have fixed an issue with `mktemp` command, which you tried to fix in your code as well. Can you try latest master?

**Comment by christian-fei** [comment]
The fix for `mktemp` works on Mac, but i still get the `-n` character at the beginning of the file.

I guess the most cross platform way to do it the would be to `cp /dev/null $CHAINED_FILENAME`

Committing now, If you like you can merge it :)

**Comment by zakjan** [comment]
One last thing :)

```
FILE_SRC_DIR=$(cd "$(dirname $1)"; pwd)
FILENAME=$(basename $1)

openssl x509 -in $FILE_SRC_DIR/$FILENAME -out $CURRENT_FILENAME
```

Is it really necessary to absolutize path to input file in such way?

**Comment by christian-fei** [comment]
I found it didn't work if executed for example:

```
sudo sh ./resolve.sh ../ssl/ssl.pem output.pem
```

I had issues with the relative path, now it works for me

**Comment by zakjan** [comment]
So now this PR can contain only the change `echo -n` -> `cp /dev/null`, right? Then I merge it.

**Comment by christian-fei** [comment]
No I meant that I solved the issue with the relative path with 

```
FILE_SRC_DIR=$(cd "$(dirname $1)"; pwd)
FILENAME=$(basename $1)

openssl x509 -in $FILE_SRC_DIR/$FILENAME -out $CURRENT_FILENAME
```

Sorry for the confusion..

**Comment by zakjan** [comment]
Ah, I see. Does this fix it for you? https://github.com/zakjan/cert-chain-resolver/commit/4318a6179b336dff9a345010ffbd7f322335d545

**Comment by christian-fei** [comment]
yep :)

**Pull request closed without merging**
