### PR TITLE
Extract x509 certificates from PKCS#7 packages

### PR DESCRIPTION
**Pull request by marcelomd**
If we cannot parse directly, we might have a PKCS#7 package, so try that too.

Ideally we would be able to detect encoding/packaging/formats/etc. before parsing. I was unable to find a way to do that reliably though.

Proposed fix for #13.

### CODE REVIEW

**Comment by marcelomd** [comment]
Okay, after the whole afternoon trying, I'm unable to build using glide =\

I built and tested with regular `go get xyz`.

```
[18:07:50] mallmann:cert-chain-resolver> export GOPATH=$(pwd)
[18:07:52] mallmann:cert-chain-resolver> go get github.com/Masterminds/glide
[18:08:11] mallmann:cert-chain-resolver> GO15VENDOREXPERIMENT=1 glide get github.com/fullsailor/pkcs7
[WARN] The name listed in the config file (github.com/zakjan/cert-chain-resolver) does not match the current location (.)
[INFO] Preparing to install 1 package.
[INFO] Importing github.com/fullsailor/pkcs7
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/codegangsta/cli.
[INFO] Fetching updates for github.com/stretchr/testify.
[INFO] Fetching updates for github.com/fullsailor/pkcs7.
[INFO] Resolving imports
[INFO] Not found in vendor/: github.com/zakjan/cert-chain-resolver/certUtil (1)
[INFO] Fetching github.com/Masterminds/vcs into /Users/marcelomallmann/work/cert-chain-resolver/vendor
[INFO] Fetching gopkg.in/yaml.v2 into /Users/marcelomallmann/work/cert-chain-resolver/vendor
[INFO] Fetching github.com/Masterminds/semver into /Users/marcelomallmann/work/cert-chain-resolver/vendor
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/zakjan/cert-chain-resolver.
[18:08:36] mallmann:cert-chain-resolver> GO15VENDOREXPERIMENT=1 glide install
[WARN] The name listed in the config file (github.com/zakjan/cert-chain-resolver) does not match the current location (.)
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/fullsailor/pkcs7.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/Masterminds/vcs.
[INFO] Fetching updates for github.com/Masterminds/semver.
[INFO] Fetching updates for github.com/codegangsta/cli.
[INFO] Fetching updates for github.com/stretchr/testify.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[INFO] Setting version for github.com/Masterminds/vcs to 7af28b64c5ec41b1558f5514fd938379822c237c.
[INFO] Setting version for github.com/fullsailor/pkcs7 to 2585af45975b11f1d7502bb6c01556c29efb54ce.
[INFO] Setting version for github.com/codegangsta/cli to 3a52a3b8124e194986964c547054f0a7b8f56892.
[INFO] Setting version for github.com/stretchr/testify to 6cb3b85ef5a0efef77caef88363ec4d4b5c0976d.
[INFO] Setting version for github.com/Masterminds/semver to 7e56b5cd00f9666fc899aa9c11c9a7d51f2a9995.
[INFO] Setting version for gopkg.in/yaml.v2 to a83829b6f1293c91addabc89d0571c246397bbf4.
[18:08:44] mallmann:cert-chain-resolver> GO15VENDOREXPERIMENT=1 go build
main.go:5:2: cannot find package "github.com/codegangsta/cli" in any of:
    /usr/local/Cellar/go/1.5.3/libexec/src/github.com/codegangsta/cli (from $GOROOT)
    /Users/marcelomallmann/work/cert-chain-resolver/src/github.com/codegangsta/cli (from $GOPATH)
main.go:6:2: cannot find package "github.com/zakjan/cert-chain-resolver/certUtil" in any of:
    /usr/local/Cellar/go/1.5.3/libexec/src/github.com/zakjan/cert-chain-resolver/certUtil (from $GOROOT)
    /Users/marcelomallmann/work/cert-chain-resolver/src/github.com/zakjan/cert-chain-resolver/certUtil (from $GOPATH)
```

**Comment by dbiazus** [comment]
👍

**Comment by zakjan** [comment]
Hi, thank you for your contribution. Can you include [tests](https://github.com/zakjan/cert-chain-resolver/blob/master/tests/run.sh) in this PR? I have fixed the CircleCI build script.

Btw, building probably didn't work for you, because the repo needs to be cloned in `$GOPATH/src`. See https://github.com/golang/go/issues/12511. Also `GO15VENDOREXPERIMENT` is now no longer needed with Go 1.6, it is default behavior.

**Comment by marcelomd** [comment]
Yay again! 🍻

**Comment by zakjan** [comment]
> This branch has conflicts that must be resolved

**Comment by marcelomd** [comment]
Should work now.

**Comment by zakjan** [comment]
There is still a merge conflict, now commited, in tests.sh

**Comment by marcelomd** [comment]
Last time, I promise =)

**Comment by zakjan** [comment]
👍

**Pull request merged**
