### PR TITLE
Stop traversing certificate chain if the certificate is a root certificate

### PR DESCRIPTION
**Pull request by F21**
By default, the resolver will follow AIA resources until it finds a certificate that does not contain an AIA resource. This causes a problem where if the root certificate contains an AIA resource to itself, it will go into an infinite loop.

Also, I have noticed that if the intermediate certificate contains an AIA resource to the root certificate, the root certificate is included in the chain.

This PR fixes these problems by stopping the traversal if it encounters a root certificate. This is done by checking if the certificate is signed by itself as all root certificates have to be self-signed.

The expected test result for `multiple-issuer-urls.crt` was also incorrect and has been fixed.

### CODE REVIEW

**Comment by F21** [comment]
Finally got the tests passing!

**Comment by zakjan** [comment]
Great, thanks a lot!

I see you have created own certificates with localhost AIA. Do you think we should do the same for all test certs? So we don't need to rely on 3rd party certs on the Internet.

**Comment by F21** [comment]
@zakjan I am not opposed to adding more localhost certs, but I think keeping the 3rd party certs is a good thing, because the library gets exposed to more certificate variations and configurations, which will allow us to catch more problems :smile:

**Comment by zakjan** [comment]
@F21 Ok. Just one thing for now, could you regenerate those certs you added with URLs on a non-privileged port (e.g. 8080)? It would be better to run the tests without sudo.

**Pull request merged**
