### PR TITLE
Convert glide to go modules

### PR DESCRIPTION
**Pull request by fuegas**
As of Go 1.12 go modules are finalized. This change converts the use of glide to go modules.

### CODE REVIEW

**Review by zakjan — APPROVED** [review]

**Comment by zakjan** [comment]
Thanks, this is very helpful! I started it locally when Go 1.16 was released, just haven't pushed it yet. Do you think it's better to have as low as possible Go requirement (1.12), or use the latest Go?

**Comment by zakjan** [comment]
Released as 1.0.3

**Comment by fuegas** [comment]
@zakjan : I was doubting about the Go requirement as well. However, as the output of the go.mod and go.sum did not change with different versions, I opted to use the lower version so (possibly) more people can compile it.

**Comment by zakjan** [comment]
Yeah. it works with Go 1.16 anyway, so it's fine.

**Pull request merged**
