### PR TITLE
Add --include-system flag

### PR DESCRIPTION
**Pull request by marcelomd**
This flags includes the root CA certificate from the system store in the
output chain

### CODE REVIEW

**Comment by marcelomd** [comment]
Proposed fix for issue #12

**Comment by dbiazus** [comment]
👍

**Comment by zakjan** [comment]
Hi, thank you for your contribution. Can you include [tests](https://github.com/zakjan/cert-chain-resolver/blob/master/tests/run.sh) in this PR? I have fixed the CircleCI build script.

**Comment by marcelomd** [comment]
Done. Is there anything else I can do?

**Comment by zakjan** [comment]
Yeah. Please rebase to the latest master to see if tests pass :)

**Comment by marcelomd** [comment]
Yay \o/

**Comment by zakjan** [comment]
Great, thanks :)

**Comment by zakjan** [comment]
@marcelomd Ah, I see there is no documentation about this flag, can you update the readme file?

**Pull request merged**
